apiVersion: 1

datasources:
  - name: k6-influxdb
    uid: k6-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      dbName: k6
      httpMode: GET
      timeInterval: "5s"
    editable: true
